### ISSUE TITLE
Detail page - Show "content type" taxonomy in meta data

### ISSUE THREAD

**Issue by tbrlpld** [MozillaFoundation/foundation.mozilla.org#10438]
## Description

Show the related "content type" taxonomy instances in the meta data line of the detail page. 

<img width="256" alt="Screenshot 2023-04-06 at 12 28 55" src="https://user-images.githubusercontent.com/24797493/230476499-d8319ce9-5881-46d2-9280-ec2280cdaf93.png">

[Epic](https://github.com/MozillaFoundation/foundation.mozilla.org/issues/10339) | [Designs](https://www.figma.com/file/dPGD3acNbT75dvEGzNaGUb/Responsible-Computing?t=zoMb9zxg25R0T6yt-6)

## Dev task

- [x] Double check with design and stakeholders which taxonomy should be displayed. 

## Acceptance criteria

* On a detail page … 
	* as a visitor … 
		- [ ] I can see the related “content type” taxonomy instances in the meta data line next to the date below the title.
		- [ ] when there are multiple “content type” taxonomy instances, I can see they are joined with a “/”.

**Comment by beccaklam** [comment]
This looks fine to me ✅ We should just double check this is the taxonomy Joycelyn wants before this ticket goes into a sprint.

**Comment by jhonatan-lopes** [comment]
@beccaklam how should we break up large meta datas? Should it go into another line? Use ellipsis?

![image](https://github.com/MozillaFoundation/foundation.mozilla.org/assets/61277874/31117d40-5201-4873-9913-056280f7b2c0)

**Comment by Gbaldassano** [comment]
@jhonatan-lopes to close and open up bug ticket for this

**Comment by jhonatan-lopes** [comment]
Discussion regarding breaking up metadata moved to #10740

**Comment by beccaklam** [comment]
@jhonatan-lopes just confirming as I did in the other ticket that we currently have profiles displayed instead of the content type taxonomy which is what should be shown beside the date.

**Comment by jhonatan-lopes** [comment]
Thanks @beccaklam! Nice catch! There was actually an error with the code, thanks for flagging that up.

**Comment by beccaklam** [comment]
Hi @jhonatan-lopes! Just noting that on staging the cards in the curriculum library seem to be missing the author names and other taxonomies? It should only be on the detail page where the meta data is limited to content type taxonomy.

Staging:
<img width="1512" alt="Screenshot 2023-06-30 at 10 17 40 AM" src="https://github.com/MozillaFoundation/foundation.mozilla.org/assets/20977376/3a42bb91-873b-4781-b65a-dd7b662c5619">

Research Hub library card example with author name and multiple taxonomies:
<img width="1512" alt="Screenshot 2023-06-30 at 10 20 13 AM" src="https://github.com/MozillaFoundation/foundation.mozilla.org/assets/20977376/bb5c25e0-23c2-42ad-a569-8aa864cb1f26">
