### ISSUE TITLE
[FA] Clean up existing petition code

### ISSUE THREAD

**Issue by mmmavis** [MozillaFoundation/foundation.mozilla.org#10472]
We've decided to go with the HTML embed option with FormAssembly (for context see thread in #10468). Form submission will be handled by FormAssembly's own JavaScript code. This means once we have verified the new form is working, we can then remove existing petition related code.

## Acceptance Criteria
- [x] remove obsolete JS/JSX code
- [x] remove obsolete template code
- [x] remove obsolete SCSS code
- [x] remove petition related backend code that is no longer in use
- [x] remove old test code (if any)
- [x] review README and update it accordingly 

## To-Do on Staging and Prod
- [x] staging: remove old env vars from Heroku
  - [x] `CRM_AWS_SQS_ACCESS_KEY_ID`
  - [x] `CRM_AWS_SQS_REGION`
  - [x] `CRM_AWS_SQS_SECRET_ACCESS_KEY`
  - [x] `CRM_PETITION_SQS_QUEUE_URL`
- [ ] prod: remove old env vars from Heroku
  - [ ] `CRM_AWS_SQS_ACCESS_KEY_ID`
  - [ ] `CRM_AWS_SQS_REGION`
  - [ ] `CRM_AWS_SQS_SECRET_ACCESS_KEY`
  - [ ] `CRM_PETITION_SQS_QUEUE_URL`

**Comment by Gbaldassano** [comment]
TBD on sizing - discuss when @mmmavis returns

**Comment by mmmavis** [comment]
These env vars have been removed from **staging**:

- `CRM_AWS_SQS_ACCESS_KEY_ID`
- `CRM_AWS_SQS_REGION`
- `CRM_AWS_SQS_SECRET_ACCESS_KEY`
- `CRM_PETITION_SQS_QUEUE_URL`

I'm moving this ticket to `ready for prod` state!

**Comment by mmmavis** [comment]
These env vars have been removed from **prod**:

- `CRM_AWS_SQS_ACCESS_KEY_ID`
- `CRM_AWS_SQS_REGION`
- `CRM_AWS_SQS_SECRET_ACCESS_KEY`
- `CRM_PETITION_SQS_QUEUE_URL`
