### ISSUE TITLE
[FA] Implementation EPIC

### ISSUE THREAD

**Issue by mmmavis** [MozillaFoundation/foundation.mozilla.org#10532]
Replace the existing petition form with FormAssembly form.

**We will need a feature branch for this work**

# Dev Tasks

### Prep work

- https://github.com/MozillaFoundation/foundation.mozilla.org/issues/10544

### Implementation

- https://github.com/MozillaFoundation/foundation.mozilla.org/issues/10545
- https://github.com/MozillaFoundation/foundation.mozilla.org/issues/10556
- https://github.com/MozillaFoundation/foundation.mozilla.org/issues/10557
- https://github.com/MozillaFoundation/foundation.mozilla.org/issues/10558
- https://github.com/MozillaFoundation/foundation.mozilla.org/issues/10559
- https://github.com/mozillafoundation/foundation.mozilla.org/issues/10619
- https://github.com/mozillafoundation/foundation.mozilla.org/issues/10628
- https://github.com/MozillaFoundation/foundation.mozilla.org/issues/10560
- https://github.com/MozillaFoundation/foundation.mozilla.org/issues/10471
- https://github.com/MozillaFoundation/foundation.mozilla.org/issues/10470
- https://github.com/MozillaFoundation/foundation.mozilla.org/issues/10625
- https://github.com/MozillaFoundation/foundation.mozilla.org/issues/10579
- ~https://github.com/MozillaFoundation/foundation.mozilla.org/issues/10658~ 
- https://github.com/MozillaFoundation/foundation.mozilla.org/issues/10686

### After merging feature branch to `main` (pushing to staging)
- [x] Update env vars on Heroku staging instance

### After pushing to prod
- [x] Update env vars on Heroku s prod instance

### Remove old code (once we verify new form flow is working as expected)
- [x] Update `PETITION_TEST_CAMPAIGN_ID` and the hardcoded test campaign id in `tests/integration/petition/utility.js`
- [x] Rename fields https://github.com/MozillaFoundation/foundation.mozilla.org/issues/10659
- [x] Remove obsolete petition code https://github.com/MozillaFoundation/foundation.mozilla.org/issues/10472 
  - [x] Remove `petition.scss`
  - [x] Remove other old SCSS code
  - [x] Remove petition related JS code
  - [x] Remove old backend code

**Comment by simont-cr** [comment]
@mmmavis This EPIC seems to be almost done, can you review if the work that is still missing is either still valid and can be allocated for the new sprints or rather whatever is missing is now outdated and this can now be closed?

**Comment by mmmavis** [comment]
Hi @simont-cr , we can close this epic as the bulk of the work was released months ago. I would keep the two remaining tickets open (#10686 #10781) as they are still valuable to do.
