### ISSUE TITLE
[FA] Implementation Prep Work

### ISSUE THREAD

**Issue by mmmavis** [MozillaFoundation/foundation.mozilla.org#10544]
## Tasks

- [x] figure out rollout plan with the team
- [x] find out if FormAssembly can handle newsletter signup
    - keep Basket API as FormAssembly can't handle this
- [x] figure out what data needs to be sent to Salesforce
    - relevant links
        - [network-api/networkapi/campaign/views.py](https://github.com/MozillaFoundation/foundation.mozilla.org/blob/main/network-api/networkapi/campaign/views.py#L162-L228)
        - [source/js/components/petition/petition.jsx](https://github.com/MozillaFoundation/foundation.mozilla.org/blob/main/source/js/components/petition/petition.jsx)
        - [network-api/networkapi/wagtailpages/templates/wagtailpages/tags/cta/petition.html ](https://github.com/MozillaFoundation/foundation.mozilla.org/blob/main/network-api/networkapi/wagtailpages/templates/wagtailpages/tags/cta/petition.html)
        - Here's the list
            ```
            "thank_you_page_url":  required, pre-defined, no need to send to Salesforce
            "campaign_id":         required, hidden field, pre-defined
            "source_url":          required, hidden field, pre-defined
            "lang":                required, hidden field, pre-defined
            "newsletter":          required, hidden field, pre-defined
            "first_name":          required, user input
            "last_name":           required, user input
            "email":               required, user input
            "email_subscription":  required, user input 
            "country":             optional, user input,
            "postal_code":         optional, user input
            "comments":            optional, user input
            ```

- [x] create a form on FormAssembly based on the requirements

## Acceptance Criteria

- [x] Set up a FormAssembly form based on the data requirements for Salesforce data entry. 
    - (Note that we only need one form. The only difference is that the form will be connected to Salesforce sandbox during development phase. Once we are ready to push live, connector will be linked to the real Salesforce instance.)

**Comment by mmmavis** [comment]
Form has been set up on FA. Keeping this ticket open for now as there still will be some modification to the form e.g., add new field(s)

**Comment by mmmavis** [comment]
Done!
