### ISSUE TITLE
[CMS Clean Up] Deprecate Primary page

### ISSUE THREAD

**Issue by beccaklam** [MozillaFoundation/foundation.mozilla.org#10674]
_From the Page Types audit work (#10606):_

**Task:** The banner page type does everything the primary page does. To streamline the amount of page types the CMS has we are suggesting we deprecate the primary page type so editors can no longer create new primary pages.

**Acceptance Criteria**
- [x] As an editor, there is no option for me to create a primary page type in the CMS
- [x] As an editor I can still edit preexisting pages created using the primary page type
- [x] As a user I can still access preexisting pages created using the primary page type

**Comment by mtdenton** [comment]
@jhonatan-lopes assigned for grooming

**Comment by victoriachan** [comment]
@jhonatan-lopes Can you review https://github.com/MozillaFoundation/foundation.mozilla.org/pull/11120 please? It is a fairly small change. Thank you!

**Comment by mtdenton** [comment]
QA:

- Primary pages could not be created on as a child of Homepage
- "Who we are" was still editable
- Several of the existing primary page types (all that I checked) were still available and viewable
