### ISSUE TITLE
[CMS Clean Up] Deprecate Campaign page

### ISSUE THREAD

**Issue by beccaklam** [MozillaFoundation/foundation.mozilla.org#10673]
_From the Page Types audit work (#10606):_

**Task:** The banner page type does mostly everything the campaign page does. To streamline the amount of page types the CMS has we are suggesting we add a "no banner" option to the banner page type and then deprecate the campaign page.

**Acceptance Criteria**
- [ ] As an editor, I see there is an option on banner page types to hide/not show the banner image/cut out similar to how the campaign page is currently styled
- [ ] As an editor, all documentation on https://foundation.mozilla.org/en/docs/how-do-i-wagtail/ reflects this update 

_Once the banner page has the option not to show the banner image ..._

- [ ] As an editor I can longer create a campaign page page type
- [ ] As an editor I can still edit preexisting pages created using the campaign page type
- [ ] As a user I can still access preexisting pages created using the campaign page type

**Comment by kristinashu** [comment]
Note that this ticket should come after the block clean up work so the page is less overwhelming to users.

**Comment by victoriachan** [comment]
When comparing the Banner page and the Campaign page, I can see that they have rather different layout, not just that the banner page has a hero banner at the top. For example,

1. The banner page has a narrower body content column than the campaign page.
2. The campaign page has a minimal site header which hides the primary menu such as 'Who we are' 'What we do', etc.
3. The campaign page can display body content in 2 columns if it has a petition form.

How should the combined Banner page display when the "no banner" option is selected? Should it display just like the banner page, but with no hero banner? It may not look good this way. (see example below) 

----

<img width="500" alt="banner_page_new" src="https://github.com/MozillaFoundation/foundation.mozilla.org/assets/60257/841e0311-73a8-4245-abb3-01d2d76aea17">

----

Looking at the html, they have very different markup. An easy option would be to keep the 2 distinct templates, and switch to the campaign page template when the "no banner" option is selected. However this means we will still have 2 templates to maintain on the backend, and we will introduce additional complexity to QA testing and backend code.

**Comment by jhonatan-lopes** [comment]
@kristinashu what are your thoughts?

**Comment by kristinashu** [comment]
Thank you @victoriachan for looking into this! 

A banner page type with a petition on the side and no subnav items currently looks like this:

<img width="1698" alt="image" src="https://github.com/MozillaFoundation/foundation.mozilla.org/assets/1068783/6a32d7a4-4905-435b-9a0d-623076998612">

We also have a check box to make the content wide or narrow:

<img width="695" alt="image" src="https://github.com/MozillaFoundation/foundation.mozilla.org/assets/1068783/06713bce-7a7e-4511-9341-8d3a342975bb">

But given "we will still have 2 templates to maintain on the backend," it sounds like merging those won't actually help simplify things. I'm ok to close this as "won't fix." Thank you again for looking into it.

**Comment by cdanfon** [comment]
As per above comment from Kristina, closing this as 'won't fix'
