### ISSUE TITLE
[CMS Clean Up] Deprecate Initiatives page

### ISSUE THREAD

**Issue by beccaklam** [MozillaFoundation/foundation.mozilla.org#10676]
_From the Page Types audit work (#10606):_

**Task:** The [Initiatives page](https://foundation.mozilla.org/en/initiatives/) is out of date and no longer used. We are suggesting we find new homes for its child pages and then deprecating this page.

* [ ] Go through child pages of the Initiatives page and figure out which pages we need to keep
* [ ] Find new home for child pages
* [ ] Open implementation ticket to move child pages
* [ ] Open implementation ticket to deprecate Initiatives page

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/TP1-161)

**Comment by data-sync-user** [comment]
➤ Rebecca Lam commented:

Adding a note here to say this work is still relevant any future website work.

**Comment by data-sync-user** [comment]
➤ Rebecca Lam commented:

Useful link: https://docs.google.com/presentation/d/1RxNUz3PxYMDAvZ4_on011PLyYbnVpdCrWNOcehCIgfA/edit?usp=sharing ( https://docs.google.com/presentation/d/1RxNUz3PxYMDAvZ4_on011PLyYbnVpdCrWNOcehCIgfA/edit?usp=sharing|smart-link )
