### ISSUE TITLE
[EPIC] Post-Petition Donation Tracking/Customization

### ISSUE THREAD

**Issue by Gbaldassano** [MozillaFoundation/foundation.mozilla.org#10842]
### Context
The engagement team has flagged an issue they would like us to solve for related to gift-attribution and fundraising reporting. This is due to:

- UTM parameters being stripped, which leads to a discrepancy between fundraising reporting in Salesforce and in Fundraise Up
- Salesforce is underreporting our campaign-specific fundraising numbers
- We need to be able to track actual fundraising numbers by campaign within Salesforce and remove our dependency on Fundraise Up reporting 
- This aligns with our agreed upon organizational approach with Salesforce being the “source of truth”
- We need to be able to easily track petition signatures and fundraising numbers related to petition campaigns 

### Request

![Screenshot 2023-07-05 at 3.16.04 PM (1).png](https://images.zenhubusercontent.com/640f8c755e71df27c4397000/f95e966a-8d06-4637-8392-00a59bf1666a)

- Create a way to 'customize' the FRU form that shows up after a petition is signed, so that after someone signs a specific petition, they get shown a form for a specific FRU campaign to enable better tracking to Salesforce.
- Ensure the Salesforce Campaign remains attached to donations that come in this way 

### Acceptance Criteria

- [ ] After a user signs a petition, the post-petition donate modal pops up
- [ ] This modal should drive to a FRU form that is specific to the petition
- [ ] This FRU form should have a specific campaign ID that is also mapped to the same Salesforce Campaign ID
- [ ] Both the FRU campaign ID & Salesforce Campaign ID will be pushed from FRU to Salesforce will be sent to Salesforce, allowing Fundraising team to attribute which donations came from which petitions

┆Issue is synchronized with this [Jira Story](https://mozilla-hub.atlassian.net/browse/TP-82)

**Comment by simont-cr** [comment]
Closed per 2024 ticket purge.
