### ISSUE TITLE
[Epic] EOY - Needs to be live before 11/28 - Style/Implement New Donor Help Form

### ISSUE THREAD

**Issue by Gbaldassano** [MozillaFoundation/foundation.mozilla.org#10840]
### Context
Currently there are 2 donor care pages (/help/; /faq/) but the Donor Care team wants to combine these into one page and redirect the old pages.
This ticket is to begin the integration and testing for the new donor help form (FormAssembly) on the MoFo tech stack.

Old Donor Help page: https://donate.mozilla.org/help/
New Donor Help & FAQ page: https://foundation.mozilla.org/donate/help/*
password: donate

### Request
Need designer/developer help with the following in order to Implement New Donor Help & FAQ page: https://foundation.mozilla.org/donate/help/ (Was built in January by Kristina Shu and is public with password: donate)

- **Localization:** Pull language/locale code from main page URL and add it to the form into a hidden field (this will then tell us the language to reply to them in, rather than previously it was a self-select language option)
- **Styling:** Currently the new form is not styled in MoFo's brand guidelines. If possible, new donor help form styling should be updated. (New Form: https://mozillafoundation.tfaforms.net/12) 
- From Mia: There is the option to have styling built into FormAssembly as a Style Template which might help everyone building forms going forward with font and color options (so maybe could check off these two things at once). You can upload a style CSS template in Form Assembly which includes fonts, size, spacing, etc. that can be applied across forms, and then users can just select it from the dropdown. Mia worked on creating this for the Thunderbird form with their web developer (essentially the same form).
- **Integration:** Integrate new Donor Help form to replace the 'Contact Us' image and be embedded within the page
- If possible fix some conditional formatting with the reCaptcha**
- **Redirects:** Old Donor Help pages: /help/; /faq/; should redirect to the new page
- This should be built on MoFo stack, not donate stack - setting up this new page should hopefully mean we don't need to migrate as many pages from https://donate.mozilla.org/en-US/

**Captcha needs to be hid when the following options are selected from the menu: "Technical Support for Firefox or Thunderbird" and "To Request a feature for Firefox".

### Acceptance Criteria
- [x] Old pages are redirected to new page (Old Donor Help pages: /help/; /faq/)
- [x] New page is set up with new form 
- [x] Styling of form is inline with MoFo Brand
- [x] Language from URL is pulled into form (https://mozillafoundation.tfaforms.net/12)
- [ ] Fixed conditional formatting with reCaptcha

**Comment by mmmavis** [comment]
@Gbaldassano do we have the link to the Thunderbird form? I would like to check it out.

**Comment by Miaatmozilla** [comment]
@mmmavis Here is the draft of the [TB form](https://mozillafoundation.tfaforms.net/11) that will be embedded on their existing [Donor Help site](https://www.thunderbird.net/en-US/donate/help/) to replace the current embedded form

**Comment by mmmavis** [comment]
@Miaatmozilla Thanks!

**Comment by mmmavis** [comment]
Hi @Gbaldassano , I'm a bit confused about where this new form/page is going to live. In the ticket description you mentioned

> the new, combined page will still be https://donate.mozilla.org/help/

and later 

> This should be built on MoFo stack, not donate stack - setting up this new page should hopefully mean we don't need to migrate as many pages from https://donate.mozilla.org/en-US/

Are we thinking about setting up a new page on fo.mo and having https://donate.mozilla.org/help/ redirected to that newly created page?

cc @mtdenton

**Comment by Gbaldassano** [comment]
Hey @mmmavis  - apologies for the confusion! [Last I spoke to Kevin Hill about this](https://github.com/MozillaFoundation/foundation.mozilla.org/issues/10303) he specified that he wanted to keep pages on the donate.mozilla.org url, even as we migrate the tech stacks, unless there is a compelling reason to change it.

So, if we keep this on donate, the new page would still live on https://donate.mozilla.org/help/- basically replacing the old page, with the other ancillary pages redirected to https://donate.mozilla.org/help/. Does that make sense?

The other option would be to have this new page live on https://foundation.mozilla.org/donate/help/ - which I think is also fine, but would mean we should also migrate donate.mozilla.org as a whole to https://foundation.mozilla.org/en/donate  IMHO- @Miaatmozilla are you or another stakeholder able to provide direction on the URL we should use here?

**Comment by kristinashu** [comment]
Does the migration from our donate instance to our main wagtail instance need to be done before this work can be done?

**Comment by kristinashu** [comment]
Ok I see, UX-wise it could be jarring and not very trustworthy to bring people to a new site and take them away from the donate site. Could the form and copy be updated on the existing site https://donate.mozilla.org/en-US/help/ (there would be some wasted work but it would decrease the risk of loosing donations)?

**Comment by Miaatmozilla** [comment]
@Gbaldassano @mtdenton I am in favor of what Tyler has proposed, and to keep the new page on fo.mo. For the help page, it really doesn't matter too much where it lives - I don't imagine folks are finding us too much through googling, more so through links directly within the FRU donation page or our donation receipt emails. The donor care team doesn't use or have access to and analytics on our help page at the moment. 

To me it seems like the donation landing pages, https://foundation.mozilla.org/en/donate/ have a wider consideration for things like SEO than the help pages, I think Michael Whitney would be the decider on this but would need to be briefed.

**Comment by kristinashu** [comment]
Great point about the donate modal on the foundation site! It seems like we're moving away from the basic donate page donate.mozilla.org and directing people to the foundation site so having /help on the main foundation site https://foundation.mozilla.org/donate/help/ sounds good !

**Comment by Miaatmozilla** [comment]
So are we all in favor of Tyler's solution for now for the Donate Help Page?

> Yes, but in the meantime, we could set up a 301 redirect from https://donate.mozilla.org/help to https://foundation.mozilla.org/donate/help until stakeholders decide how to proceed with the possibility of using FRU landing pages since that's what is blocking the migration work at the moment.

**Comment by TheoChevalier** [comment]
Hi folks,

I just wanted to point out that localization has started on https://foundation.mozilla.org/donate/help as per discussion with @Miaatmozilla, and it would be better to avoid moving back and forth translations between two instances as there isn’t a straightforward way to do it.

This being said, another thing to take into consideration, if we keep this content on the foundation website, we’re losing ~20 locales compared to the pages on the donate stack.

**Comment by Gbaldassano** [comment]
Thanks all! Sharing an update: I chatted with Michael about this earlier today and he confirmed he is fine with hosting on https://foundation.mozilla.org/donate/help as it's more efficient for us. We should still redirect https://donate.mozilla.org/en-US/help/ to this page. 

I'll update the body of the ticket, @mmmavis apologies for the confusion!

**Comment by mmmavis** [comment]
Thanks all! I will start breaking the work into tickets.

**Comment by mmmavis** [comment]
Hello @Miaatmozilla 👋🏻 ,

I have some updates and questions that I'm hoping to get clarification on

**1. Has the form been finalized? How often will it get updated?**
Asking because every time we edit the FA form, it requires devs to manually copy the code snippet from FA and perform a series of customization hacks in our codebase for the form to show up on our sites

**2. Captcha**
I reached out to FA support to see if it's possible to conditionally enabled reCaptcha based, the answer was negative.) Here's the full response
> “Currently, it is not possible to conditionally add or remove reCaptcha from the form. I’ve already submitted a feature request on your behalf to offer it as a suggestion to our product team.”

**3. Will the standalone [FA hosted page](https://mozillafoundation.tfaforms.net/12) be shared out directly to the public?**
If we won't be directly sharing the form, styling overrides will be best to live on our repo so 1) Styling can sync well with the style guide we implemented on Foundation site and 2) have code revision tracking

**Comment by Miaatmozilla** [comment]
@mmmavis Thanks for the questions! I was able to chat on a call with Genevieve today and we worked through your questions (and raised a few more), I'm off next week so we decided it would be best to pick up after that. 
And decided that I will work with CRM to finalize and move it to production before you have to do any work.

I don't want to leave you hanging though (if you are a naturally curious person like me) so here's some thoughts:

1. FormAssembly has some [options for publishing](https://help.formassembly.com/help/publishing-options), and Genevieve mentioned she would do some more investigating to find out how we will publish forms on our sites going forward. I understand that the embedded HTML option is what we go with that would mean it's a static thing that would have to get copied over if there were any updates. So in that case updates every 6 mo. at the min would be greatly appreciated.
2. Yes, FA would tell you this - it's because they themselves don't provide support with custom code. But good news it is an option to [add it into the Form Builder](https://help.formassembly.com/help/custom-css#samples). I have code for both the 'recaptcha issue' and the 'pulling locale into the form as a hidden field' that our friends at Thunderbird have written and can share with you (just gotta figure out how). You can see it working on [that form](https://mozillafoundation.tfaforms.net/11) when you select the option "Technical Support for Thunderbird" vs. other options. 
3. The plan is not to have the stand alone page shared with the public. Happy to learn more about considerations for styling on your end, and show you/Kristina what is customizable on the FA end. Maybe it would be good to have both - have it styled on your repo and then a template created and selected by default just in case something breaks? Sounds like we will talk more about this.

**Comment by Miaatmozilla** [comment]
Hey team, just wanted to drop this in here to confirm some new decisions. I have been told from Michael and Patrick on my team that we should **not** be re-directing away from the https://donate.mozilla.org/en-US/ways-to-give/ page. They want to keep that page as is for now (with update in the future to the content). 

So just the following two places will be replaced by the new page.
- https://donate.mozilla.org/en-US/help/
- https://donate.mozilla.org/en-US/faq/

Looking to know if this will affect anything.

**Comment by Miaatmozilla** [comment]
@mmmavis @mtdenton Hey I was thinking a bit more about some of the considerations we talked about last week with regards to captcha hiding and the UX of the form. 

I wanted to suggest that I remove the two dropdown options (and respective conditional text) from the form completely as a solution to avoiding the captcha hacks and also maybe help with the dropdown list being generally too long:
- [Technical support for Firefox or Thunderbird](https://mozillafoundation.tfaforms.net/12)
- [To request a feature for Firefox](https://mozillafoundation.tfaforms.net/12)

Upon consideration, the containing page layout is much more detailed and has the [support boxes right below](https://foundation.mozilla.org/en/donate/help/) so it probably makes the most sense to just remove these picklist options. Sometimes the thing staring you in the face is the least obvious haha. 

Hopefully this will help us get towards deploying the form/website sooner. Let me know and we can move forward :)

**Comment by mmmavis** [comment]
Thanks for letting us know @Miaatmozilla ! This def helps simplify implementation 😁 

I've drafted an implementation plan and would like to get some feedback 
(tagging everyone on this ticket @Miaatmozilla @Gbaldassano @kristinashu @mtdenton @TheoChevalier )

1. Mia and team to finalize form on FormAssembly
2. Decide what StreamBlocks (Wagtail blocks) we want to allow on this new page type we are creating (let's call it `DonateHelpPage` for now)
3. Decide where we want to send users to after they have submitted the form
4. Dev team starts creating the new page type `DonateHelpPage` on Foundation stack
   - New page type `DonateHelpPage` will have a hardcoded section which renders the FA donate help form https://mozillafoundation.tfaforms.net/12
   - The rest of the page can be edited on CMS
   - **Dev Tickets**
       (Create a feature branch)
     1. Create DonateHelpPage model and a blank page template for it
     2. Set up the template with hardcoded section (FA Form) and layout
     3. Set up visual regression test & integration tests (Q: Should automated test submission go to Salesforce sandbox or prod?)
     4. Work with designers to make the form and page more aligned with our branding
     5. Get localization working (wrap hardcoded text in template with i18n tags) 
     6. Get stakeholders' feedback on the feature branch before we merge work into `main` branch (i.e., before we push the work to Foundation staging site)
5. Work has been merged and deployed to staging. Dev team to let stakeholders know that this is ready for QA on staging.
   - fix bugs if there's any
6. Dev team to deploy work to production.
7. Dev team to notify stakeholder the page can be building on production Foundation site CMS now.
8. Content has been entered & page has been published.
9. Dev team sets up redirects
10. Work is done. Celebrate! 🎉 🎉 🎉 🎉 🎉

**Comment by Miaatmozilla** [comment]
@mmmavis Yay this looks great. Thank you! So grateful for all your help

RE:
1. Confirming that I've finalized the form copy, last step is switching out the sandbox Salesforce instance for the production one. I'll confirm once that's done.
3. Not sure if I'm to weigh in on the redirect. I'd be fine with keeping people on the Donate Help page.  

Questions:
- We want to add another FAQ point to the list because of an update to our refund policy. Is now the time to add this?
- Under the 'Quick Links' section we also need to make a couple copy changes, notably want to change the VPN box to Mozilla Foundation (also will need an image @kristinashu). Can we make this change now as well? @TheoChevalier 
- We'd like to add anchor links to "Frequently Asked Questions" and "Where do I send a check?" so we can send folks directly to that spot on the page with a url.

**Comment by TheoChevalier** [comment]
@mmmavis I would add two steps between 5 & 6: “Form translation starts” and “Form translation is complete” as the form translations will get deployed alongside code during the production deploy.
Alternatively, we can schedule a second production deployment right before step 9.

@Miaatmozilla Feel free to make this change now, yes.
A quick note about anchor links, they will be different in each language as the anchor will be generated from the translated text

**Comment by Miaatmozilla** [comment]
**Step 1 is done!** 
[Form](https://mozillafoundation.tfaforms.net/12) is connected to production and [Page](https://foundation.mozilla.org/donate/help/) published in wagtail with copy edits. 

@mmmavis  Just following up from the idea we had in the meeting, is there a plan at all to have the optional banner on the page for any last minute announcements? We don't forsee any copy needed at the moment but just so I can bring it back to my team let me know if that's something that's getting added in as an optional element or if you prefer still for us to make a request the next time we need something like this

**Comment by danielfmiranda** [comment]
Hi @kristinashu! I was wondering if you could please help me answer two questions that I have regarding this ticket:

1. My first question is: Do we have any mock-ups regarding what this form/page should look like?

2. My second question is: What streamfields/blocks should be made available to this page type? 

    To help, here is a table showing all blocks available to `Campaign`, `Blog`, and `Article` pages. Should this new `DonateHelpPage` copy any of these?
  
    | Campaign Page         | Blog Page             | ArticlePage          |
    |-----------------------|-----------------------|-----------------------|
    | paragraph             | accordion             | accordion             |
    | card_grid             | paragraph             | airtable              |
    | image                 | card_grid             | datawrapper           |
    | image_text            | image_grid            | callout               |
    | image_text_mini       | iframe                | content               |
    | image_grid            | image                 | card_grid                 |
    | video                 | audio                 | image          |
    | iframe                | image_text            | double_image      |
    | linkbutton            | image_text_mini       | full_width_image                |
    | spacer                | video                 | iframe            |
    | single_quote          | linkbutton            | linkbutton          |
    | pulse_listing         | looping_video         | single_quote                |
    | profile_listing       | pulse_listing         | slider                 |
    | profile_by_id         | single_quote          | table                 |
    | profile_directory     | slider                | video        |
    | recent_blog_entries   | spacer                | advanced_table                       |
    | blog_set              | airtable              |                       |
    | airtable              | datawrapper           |                       |
    | typeform              | typeform              |               |
    | datawrapper           |                       |   |
    | listing               |                       |    |
    | profiles              |                       |          |
    | article_teaser_block  |                       |     |
    | group_listing_block   |                       |       |
    | image_feature         |                       |       |
    | image_teaser_block    |                       |              |
    | text_only_teaser                      |                       |                       | block_with_aside
    | accordion                      |                       |

**Comment by danielfmiranda** [comment]
Hi @kristinashu thank you! I think I will give styling it a go first, and will reach out if I have any questions 👍

**Comment by Gbaldassano** [comment]
@danielfmiranda just a heads up - i updated the body of the ticket to remove the request to redirect the 'ways-to-give' page from this - the Engagement team has some plans to update that page so let's keep that separate for now.

**Comment by danielfmiranda** [comment]
Thanks @Gbaldassano!

**Comment by danielfmiranda** [comment]
Hi @Miaatmozilla! 

To answer some of your questions from the comment above:

> We want to add another FAQ point to the list because of an update to our refund policy. Is now the time to add this?
- I can make this change at any time through the CMS, if you would like to comment the copy of the new FAQ point, I would be happy to update the current page, and also make sure that the new page includes the same.

> Under the 'Quick Links' section we also need to make a couple copy changes, notably want to change the VPN box to Mozilla Foundation (also will need an image @kristinashu). Can we make this change now as well? @TheoChevalier 
- Same response as above

> We'd like to add anchor links to "Frequently Asked Questions" and "Where do I send a check?" so we can send folks directly to that spot on the page with a url.
- It looks like the "Frequently Asked Questions" heading has an ID of `frequently-asked-questions`, so you can send users to the url with the addition of `url/#frequently-asked-questions` and it will link as expected. As for the "Where do I send a check?" section, I am going to need to investigate a little more.

**Comment by Miaatmozilla** [comment]
@danielfmiranda Great thanks, the changes have already been published on the CMS page I have access. I'm probably  confused, but are you building a new page, or working off this one that is in the CMS - [Donate Help](https://foundation.mozilla.org/en/donate/help/)?

[Mozilla Foundation - Donate Help - CMS.pdf](https://github.com/MozillaFoundation/foundation.mozilla.org/files/12730217/Mozilla.Foundation.-.Donate.Help.-.CMS.pdf)

Attached is a screenshot, in GREEN are the changes that have been made that were referenced above.

One last thing is about the call out box at the top - in RED. Is it possible to have a on/off toggle for this block since we only want to display this if there is an issue?

**Comment by danielfmiranda** [comment]
Hi @Miatatmozilla!

To answer the second question first, we can defini 

We are building a new page type specifically for a "donate help" page, but it will be quite similar to the page that we have live now in terms of fields that are available for use in the body section. The only difference will be that the call out box at the top will be hardcoded/localized,  and that the Form Assembly form will be working!

Regarding your question about the call out box at the top, we can definitely do that. Do you have any preference as to what this checkbox should be titled in the CMS? Or, would something along the lines of "show_delay_notice" work?

Thanks!

**Comment by Miaatmozilla** [comment]
@danielfmiranda Awesome, thanks for letting me know. 

The call out box, can we call it "show_notice" or "announcement". The intent is that it can be a notice box for anything Donor Care related, probably mostly used for delay in response notices to start, but also maybe for other things later on.

**Comment by danielfmiranda** [comment]
Sounds great @Miaatmozilla!

I will call it "show_notice".

To keep this ticket/work moving forward, it will first be related to just the delayed response message, but I will create a ticket so that we can implement the custom notices in the near future after this page goes live!

**Comment by Miaatmozilla** [comment]
@danielfmiranda at this stage, how annoying would it be to replace anywhere that there is the URL: https://foundation.mozilla.org/donate/help/?form=donate
to one with UTMs: https://foundation.mozilla.org/?form=donate&utm_medium=web&utm_source=faq-page&utm_campaign=23-Donor-Care&utm_term=en
?

**Comment by danielfmiranda** [comment]
@miaatmozilla not annoying at all, I have updated the existing page, and have also updated any existing links in my work so far!

**Comment by danielfmiranda** [comment]
Hi @kristinashu! 

After looking further into FormAssembly and how we have implemented it in the past, it appears that through the use of CSS, we are able to style these forms quite close to MoFo design standards.

An example would be [petition pages](https://foundation.mozilla.org/en/campaigns/venmo-put-our-privacy-first/), as this page type now features a custom-styled FormAssembly form.

If its not too much trouble, I was wondering if you could please help me by mocking up the ideal state of the help form as mentioned in the comments above?

That way, I can take a look and update the CSS to match the designs as closely as I can.

Thank you in advance!

**Comment by kristinashu** [comment]
@danielfmiranda it isn't final but here is my first pass on the design based on our Design System. I've also tagged you in the [Figma file. ](https://www.figma.com/file/ueNCG5v3GI8Zc2XmFaNyVS/Donate?type=design&node-id=610%3A35&mode=design&t=yDNxyPC9kqfu13Sa-1) 

![Donate Help Page](https://github.com/MozillaFoundation/foundation.mozilla.org/assets/1068783/d20b2231-5165-4921-9dd0-1db9b65ed015)

**Comment by danielfmiranda** [comment]
Hi @kristinashu this is the epic that houses the donate help page work that I mentioned earlier today during stand up. 

There is a PR that has been created for the donate help page feature branch and it can be found here: https://github.com/MozillaFoundation/foundation.mozilla.org/pull/11359

Do you think you can please take a look at the review app links found in the PR description and let me know if everything looks OK? 

Thanks!

**Comment by kristinashu** [comment]
The page looks great, thank you @danielfmiranda!
