### ISSUE TITLE
[PNI Privacy Index] Refine design explorations into mockups/prototypes

### ISSUE THREAD

**Issue by nancyt1** [MozillaFoundation/foundation.mozilla.org#10955]
After initial wireframe feedback stakeholders like the quiz centric version prioritizing conciseness. 

- [x] Structure draft content
- [ ] Create tablet and mobile screens https://github.com/MozillaFoundation/foundation.mozilla.org/issues/11074
- [x] Explore visual assets in ticket #10954
- [ ] Create list of what visual assets might be needed & Add in visual assets https://github.com/MozillaFoundation/foundation.mozilla.org/issues/10982
- [ ] Prototype animated elements
- [x] Get feedback from designers and devs
- [ ] Finalize https://github.com/MozillaFoundation/foundation.mozilla.org/issues/11072

**Comment by nancyt1** [comment]
Shared current [mockups](https://www.figma.com/proto/idw7tpYbaRXCRqzk01poEX/Privacy-Index-Page?page-id=388%3A3846&type=design&node-id=440-7075&viewport=-103%2C551%2C0.09&t=njDicDeXHLTuk9ov-1&scaling=scale-down-width&starting-point-node-id=440%3A7075&mode=design) with stakeholders and notes were taken in the [doc](https://docs.google.com/document/d/1sUoxksEJuD9twToptwiSOURIrmMHE91N2q-WLDbhw3w/edit#heading=h.4wefaeyrxofh).

**Comment by kristinashu** [comment]
Stakeholders continue to update the copy [here](https://docs.google.com/document/d/1xY3-NacjCfaMKoYM1EHhd6KNhPRowkdKnGwd5PBd5TA/edit#heading=h.wn4qv8s5ucbw).

**Comment by kristinashu** [comment]
Remaining work has been divided up in the individual tickets!
