### ISSUE TITLE
Create Form Assembly theme(s)

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/foundation.mozilla.org#11196]
[Request from Mary Helen.](https://mozilla-hub.atlassian.net/browse/MOFOTP-95) Aiming for end of Feb deadline but this is flexible. 

We will no longer be using Typeform and will be using Form Assembly instead because it better connects with Salesforce. We would like the forms to look and feel like our mofo brand.

Teams are sending out surveys like [this](https://mozillafoundation.tfaforms.net/27) but they don't reflect our branding. Form Assembly seems to allow for a lot of styling so we should create a template with our logo, fonts, colors, etc and direct staff to use that template.

Login info is in 1password

### Todo
- [x] Learn how to use it and what styling is possible
- [x] Create a Mozilla branded template for for staff to use
- [ ] Update documentation and share with staff
- [ ] If possible, template should link back to the foundation site
- [x] Update the PNI form styling

Related tickets
- https://github.com/MozillaFoundation/Design/issues/798
- https://github.com/MozillaFoundation/foundation.mozilla.org/issues/11186

┆Issue is synchronized with this [Jira Story](https://mozilla-hub.atlassian.net/browse/TP-116)

**Comment by kristinashu** [comment]
Great question @mmmavis! I assumed it was just for FA hosted pages. Does that sound right @Gbaldassano or will we know more and decide after the audit https://github.com/MozillaFoundation/foundation.mozilla.org/issues/11186?

**Comment by Gbaldassano** [comment]
@mmmavis @kristinashu the goal would be to have Form Assembly be able to replace how stakeholders have been using Type form, which from my understanding what I've seen so far is to spin up pages like https://mozillafoundation.typeform.com/to/xm6oqkYH 

Are Form Sssembly pages the equivalent here? Would enabling stakeholders to spin up their own FA-hosted pages cause any issues for our FA set up so far?

**Comment by kristinashu** [comment]
@Gbaldassano I think what @mmmavis is getting at is that we currently have two options with TypeForm:
1) TypeForm hosted that are not on our site (like what you linked to https://mozillafoundation.typeform.com/to/xm6oqkYH)
2) TypeForm on our site using our CMS block (e.g. https://foundation.mozilla.org/en/blog/could-you-be-the-next-common-voice-language-rep/)

We created the CMS block on our site to encourage staff to embed the form on our website so they can direct people to our site (to increase the chances of deepening their engagement and getting newsletter signups / donations) rather than a stand alone link. However, it doesn't seem as though staff have made much use of this.

A Form Assembly equivalent of https://mozillafoundation.typeform.com/to/xm6oqkYH would be https://mozillafoundation.tfaforms.net/16

**Comment by kristinashu** [comment]
Mary Helen has submitted this as [a request](https://mozilla-hub.atlassian.net/browse/MOFOTP-95) and I've updated the first comment to reflect.

cc @abi-mofo

**Comment by kristinashu** [comment]
TypeForm no longer works so we've updated it with Form Assembly. Once we have a new template then we should go back and update the PNI form with the new styling https://github.com/MozillaFoundation/foundation.mozilla.org/issues/11833

**Comment by nancyt1** [comment]
_Summary_ 
It seems like you can customize most design aspects of the form and it's mostly done through custom CSS. This FA documentation page gives you [selectors](https://help.formassembly.com/help/theme-customization-controls) you can use for their teme customization and some for [custom CSS.](https://help.formassembly.com/help/custom-css). 

I created a new theme called **"MoFo Theme"** and was able to add our logo, update the font, font size, and colors to match branding but some other updates will require dev help. I created a test form called "[(TEST) Pni](https://mozillafoundation.tfaforms.net/38)" and will get feedback before sharing with the wider org. Editing the theme on FA can be a little finicky so i'd recommend saving often if you're editing directly in the Custom CSS field.

**Other things we can update with dev help:**
- Add more padding to form fields
- Adding custom footer to include contact info and redirects to foundation.mozilla.org

**Comment by kristinashu** [comment]
Thank you so much @nancyt1 for working on this! It feels much more on brand now. What do you think about making the mozilla logo link to the foundation site (if easily possible)?

**Comment by nancyt1** [comment]
@kristinashu That's a great idea! I'll have to ask mavis since that has to done through custom code.

**Comment by nancyt1** [comment]
Updated the [PNI product form](https://mozillafoundation.tfaforms.net/34)!

**Comment by mmmavis** [comment]
I can take a closer look at what's possible. @nancyt1 do you mind listing out the todos (and labeling them with priority if possible)?

**Comment by nancyt1** [comment]
@mmmavis 

**Things I'd like to Add:**
1. Add more padding to form fields, ~16px all around the text inside the text box.
2. Making the logo at the top linkable to foundation.mozilla.org

**Comment by mmmavis** [comment]
Hey @nancyt1 ,

I was able to add padding within the text fields. Let me know if you'd like to fine-tune the spacing.

For making the logo hyperlinked - I reached out to FA support and they told me it's currently not possible with the theme builder. They suggested us to go with the "predefined content" route but I haven't dived into the doc yet. Please see below for my chat history with them.

![image (6)](https://github.com/MozillaFoundation/foundation.mozilla.org/assets/2896608/676ff3ee-e6ff-41da-8f90-09608dd64ebc)

**Comment by nancyt1** [comment]
Thank you @mmmavis! 
I think the form is in a good spot now branding wise. If we wanted to do more with a custom footer or linking mofo to the logo, that might require more time and dev help and I'd open a new ticket for it.
