### ISSUE TITLE
Finalize design for donate alert banner

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/foundation.mozilla.org#11247]
The donate alert banner is now editable in the cms https://github.com/MozillaFoundation/foundation.mozilla.org/issues/9823 and the front end work will happen in https://github.com/MozillaFoundation/foundation.mozilla.org/issues/11180

We need to adapt the design to be as robust as possible so that it will work for a variety of image backgrounds.

Timeline: very firm launch date of before Black Friday on Nov 24 (design deadline Oct 25 to give time for dev to groom before Oct 30 sprint)

Initial design that needs to be tested
<img width="909" alt="image" src="https://github.com/MozillaFoundation/foundation.mozilla.org/assets/1068783/f700536f-e369-429c-8bd1-ccaba7643499">

[Figma file](https://www.figma.com/file/2TK8tXeDIiLC67TMdbMIcO/Fundraising?type=design&node-id=1537%3A48&mode=design&t=geVgZOGKnj6wYfDR-1)

### Todo's
- [x] @Gbaldassano to get example copy from Michael (max character limit: 60 for the title and 80 for the body)
- [x] Shannon to explore several graphic directions and get feedback from design and Michael
- [x] Shannon and design to stress test graphics to see if they will work responsively with text
- [x] Design to clean up Figma file and styles
- [ ] Design to update dev ticket with specs and requirements https://github.com/MozillaFoundation/foundation.mozilla.org/issues/11180 (be sure to include max character limits that factor in localization, how the image should crop (from center))

**Comment by Gbaldassano** [comment]
Sharing the example copy Michael provided here:  https://docs.google.com/document/d/1jmdXCcAvb0o-hvYDhfbIn1U7qiT2LPelpB8LQ_z8YFM/edit

**Comment by kristinashu** [comment]
I've cleaned up the [Figma file](https://www.figma.com/file/2TK8tXeDIiLC67TMdbMIcO/Fundraising?type=design&node-id=1537%3A48&mode=design&t=JOkvb5WZKVrTDVE2-1) a little and updated the copy to reflect a version from Michael. Shannon is working on the background graphics and will test them out to see which layout and colours will be the most versatile.

**Comment by kristinashu** [comment]
Feedback from Michael separated into layout and graphic:

The goal of the banner is to catch peoples’ attention before they go on with their business on the site, and it feels like this doesn’t do it at all, especially when it’s paired with the high-contrast holiday guide promo. in general it feels well-behaved and blended in, not something to grab you and stand out and be loud and get you to donate.specifically:

### Layout
- [ ] the right side text is too small to be readable. it needs to be significantly bigger.
- [ ] the black text is also blending in too much. it’s hard to see and won’t do the job of grabbing people’s attention.
- [ ] the left side text feels like it’s floating and i am inclined to want to make it longer because of how it looks. maybe we can also bold it?
- [ ] if we use anything like the colors in the background image, we need a lot more contrast to make the text pop - purple blending into purple in the headline and the button.
- [ ] i assume there’s nothing that we can do to like, force the left side text on to two lines of Donate to Mozilla today. / It’s time to reclaim the internet.
- [ ] the mobile view lacks any kind of visual tie in. again it blends in instead of standing out.
- [ ] on mobile the button text size feels like it’s being drowned out with the size of the button - can we either fix the size or bolding? or maybe we just use longer text here too.on the image itself:

### Graphic
- [ ] i don’t know what kind of story the plus signs, grid, and curves are telling when it comes to mozilla or our brand or messages we’ll be using.
- [ ] the colors are fairly passive and calm and quiet, which doesn’t get to our goal of grabbing attention.
- [ ] i don’t think the rocket makes sense in this context either. we’re going to be using language around reclaiming the internet, building our community, reaching goals, etc. - the rocket doesn’t connect to how we talk about mozilla for me.

**Comment by kristinashu** [comment]
Updated:

> the right side text is too small to be readable. it needs to be significantly bigger.

Made it bigger and bolder

> the black text is also blending in too much. it’s hard to see and won’t do the job of grabbing people’s attention. if we use anything like the colors in the background image, we need a lot more contrast to make the text pop 

Because the image is CMS editable, the text color needs to be as flexible as possible to work with as many backgrounds as possible. Black is our safest bet. For now I’ve lightened the background so there’s more contrast with the text but Shannon can revisit. 

> the left side text feels like it’s floating and i am inclined to want to make it longer because of how it looks. maybe we can also bold it? i assume there’s nothing that we can do to like, force the left side text on to two lines of Donate to Mozilla today. / It’s time to reclaim the internet.

Made it bolder

Updated with this new copy but you are correct, we can’t force the line break. It happens to line break as desired in this example but that won't be the case across different browsers, screen widths or languages.

> purple blending into purple in the headline and the button.

I’m open to using a different color button but again, it will need to be versatile enough to stand out against the various background images that will be uploaded in the CMS. Since we can’t predict what those images will be, I’d recommend using the purple and creating/choosing images what will work best with it.

> the mobile view lacks any kind of visual tie in. again it blends in instead of standing out.

For now, I’ve also faded the background image on mobile so the text stands out more and made the text bigger and bolder.

> on mobile the button text size feels like it’s being drowned out with the size of the button - can we either fix the size or bolding? or maybe we just use longer text here too.

The full width button on mobile is part of our design system so it should remain full width but I’ve made the text slightly longer, feel free to offer other copy suggestions (although this will be editable in the CMS).

> on the image itself:

I’ll let Shannon replay to the image feedback but perhaps a bigger conversation and brief is needed for the EOY graphics work.


![Desktop Layout 3](https://github.com/MozillaFoundation/foundation.mozilla.org/assets/1068783/f641afed-1fc9-404f-99d6-b9d2e240c89c)

<img width="300" alt="image" src="https://github.com/MozillaFoundation/foundation.mozilla.org/assets/1068783/06a4c9cc-8c27-4690-88ab-7bd0d93473c5">

![Desktop Layout 3 German](https://github.com/MozillaFoundation/foundation.mozilla.org/assets/1068783/098a0ca2-01a2-4a8d-a272-93d75b2e01b1)

<img width="300" alt="image" src="https://github.com/MozillaFoundation/foundation.mozilla.org/assets/1068783/dcf50b66-c1a0-4808-af42-a20126d5f7b9">

**Comment by kristinashu** [comment]
This design has been approved and dev ticket has been updated https://github.com/MozillaFoundation/foundation.mozilla.org/issues/11180
