### ISSUE TITLE
[Epic] Main Navigation Drop Down | Planning & Admin

### ISSUE THREAD

**Issue by tessheinricks** [MozillaFoundation/foundation.mozilla.org#11322]
This Epic will capture activities that involve the planning & research tasks for the Research Phase of the Main Navigation Drop Down project

Included: 

Set up meeting with Dev (Tyler, Jhonatan, Nancy) #11329 
Set up meeting with Genevieve #11266 
Resolve any outstanding PRD updates and signoffs #11346 
- [x] Set up calendar hold for shareback meetings
- [x] Set up calendar holds for Dev sync meetings
- [x] Decide where future scope or features list lives
- [x] Create [future scope document](https://docs.google.com/document/d/19Cft9KoX-lCrufvP4fxe2EZ74dB6EyRHHt1PBewL4wY/edit)

**Comment by tessheinricks** [comment]
Future Roadmaps will be documented [here ](https://docs.google.com/document/d/19Cft9KoX-lCrufvP4fxe2EZ74dB6EyRHHt1PBewL4wY/edit)

**Comment by tessheinricks** [comment]
Dev Sync holds have been scheduled for November 27th (which will connect on measuring baselines, wireframe designs, and additional considerations) & December 19th (which will review the work to date in order to provide feedback and input on the project prior to the winter shutdown).

**Comment by tessheinricks** [comment]
Both Shareback meetings have been scheduled by Genevieve.

Main Navigation Drop Down | Phase 1 Shareback | Research - Scheduled for November 27th
Main Navigation Drop Down | Phase 2 Shareback | Designs, Testing & Next Steps - Scheduled for December 13th
