### ISSUE TITLE
Create "content owner" spreadsheet 

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/foundation.mozilla.org#11716]
**Problem:** The lack of clarity around who is responsible for updating content on our site has been flagged by a few people across the org and a lot of the evergreen content on our site has become out of date. While the design team is working to update our IA and we can help staff across the org to structure and layout their content, we need staff to be responsible for the content strategy on the site, to write copy and to unsure the content is up to date.

**Solution:** I've started [a spreadsheet](https://docs.google.com/spreadsheets/d/1mjdKW8QZGYBNzIR6KfKRBHA4J1-ShSadkHtHAU6ysM8/edit#gid=0) to start identifying content owners for all our key website pages. 

**Todos**
- [x] Share with web team for feedback and input
- [x] Share with Audrey for feedback and input
- [x] Share in #web-working-group for feedback and input
- [ ] Reach out to each owner to inform them
- [x] Define what it means to be a content owner
- [ ] Check in with owners regularly

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/TP1-233)
