### ISSUE TITLE
Migrate links in blocks to `LinkBlock`/`wagtail-link-block`

### ISSUE THREAD

**Issue by jhonatan-lopes** [MozillaFoundation/foundation.mozilla.org#11955]
### Describe the feature request
Migrate current implementation of URLs/links in Wagtail blocks away from `CharBlock`/`URLBlock` towards using either `LinkBlock` or `wagtail-link-block`. This will give us better validation and the ability to handle several types of links.

The following blocks need to be migrated:

List of blocks that use a `CharBlock` or `URLBlock` for links:

* [ ]  `CardGridBlock` —> `link_url` and `link_label`
* [ ]  `AnnotatedImageBlock` → `captionURL`
* [ ]  `ImageTextBlock` → `url` and `text`
* [ ]  `ImageGridBlock` → `url`
* [ ]  `VideoBlock` → `url` (*this one might be kept as it is, since videos are assumed to always be external) and `captionURL`
* [ ]  `iFrameBlock` → `url` and `captionURL`
* [ ]  `ListingCard`/ `ListingBlock` → `link_url` and `link_page`
* [ ]  `GroupListingCard` → `url`
* [ ]  `ImageTeaserBlock` → `url_label` and `url`
* [ ]  `TextOnlyTeaser` → `link_page` and `link_url`
* [ ]  `BlockWithAside` → `"listing"` (`ListingBlock`)
* [ ]  `BlogIndexCalloutBoxBlock` → `link_button_url`
* [ ]  `GroupLIstingBLock` → `cards` → `GroupListingCard` → `url`

### Additional context
Sample implementation: https://github.com/MozillaFoundation/foundation.mozilla.org/pull/11954

See spike in https://github.com/MozillaFoundation/foundation.mozilla.org/issues/10905

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/TP1-60)
