### ISSUE TITLE
Migrate links in Mozfest blocks to `LinkBlock`/`wagtail-link-block`

### ISSUE THREAD

**Issue by jhonatan-lopes** [MozillaFoundation/foundation.mozilla.org#11956]
### Describe the feature request
Migrate current implementation of URLs/links in Mozfest blocks away from `CharBlock`/`URLBlock` towards using either `LinkBlock` or `wagtail-link-block`. This will give us better validation and the ability to handle several types of links.

The following blocks need to be migrated:

* [x]  `CarouselTextBlock` ([TP1-830](https://mozilla-hub.atlassian.net/browse/TP1-830))
  * [x]  `link_url` and `link_label`
* [x]  `CTABlock` ([TP1-831](https://mozilla-hub.atlassian.net/browse/TP1-831))
  * [x]  `link_url`
* [x]  `MixedContentBlock` ([TP1-832](https://mozilla-hub.atlassian.net/browse/TP1-832))
  * [x]  `link_url`
  * [x]  `cards`
    * [x]  `link_url`

### Additional context
Sample implementation: [https://github.com/MozillaFoundation/foundation.mozilla.org/pull/11954](https://github.com/MozillaFoundation/foundation.mozilla.org/pull/11954)

See spike in [https://github.com/MozillaFoundation/foundation.mozilla.org/issues/10905](https://github.com/MozillaFoundation/foundation.mozilla.org/issues/10905)

┆Issue is synchronized with this [Jira Epic](https://mozilla-hub.atlassian.net/browse/TP1-59)
