### ISSUE TITLE
Main Navigation Dropdown | Post Launch Items

### ISSUE THREAD

**Issue by jhonatan-lopes** [MozillaFoundation/foundation.mozilla.org#11978]
### Describe the feature request
Updating the main navigational structure and UI design for [foundation.mozilla.org](https://foundation.mozilla.org/) to improve discovery, findability, and engagement of MoFo content by efficiently guiding people where they want to go and optimizing how our staff's work and opportunities are featured.

[Tech spec document](https://docs.google.com/document/d/1UVdu7rF58cWdvNEz72HDLfipLd1D_j2VPOy8xCcgZrY)

### Terminology
| Term                            |                                                                                          Description                                                                                         |                                                Examples                                               |
|---------------------------------|:--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------:|:-----------------------------------------------------------------------------------------------------:|
| Main nav item                   |                                                                                 Main items in navigation bar                                                                                 |                                 “Who we are”, “What we do”, “Blog” [1]                                |
| Dropdown                        |                                                                             A group of sub-items under a nav item                                                                            |                                                  [2]                                                  |
| Dropdown button                 | Optional call-to-action navigation item to see all contents for that dropdown. The label on the button can be customized. Can be used alone or in conjunction with a title/description combo |                                           “Learn more ￫” [3]                                          |
| [Dropdown] Column               |                                                                 A subgroup in a dropdown that has their own navigation items                                                                 |         “Connect people”, “Rally communities”, “Influence policies”, “Research & analysis” [4]        |
| [Dropdown] Column title         |                                                                                     The name of a column                                                                                     |         “Connect people”, “Rally communities”, “Influence policies”, “Research & analysis” [5]        |
| Column button                   |                                                             Optional navigation item to redirect to contents of the whole column                                                             |                                        “See all research ￫” [6]                                       |
| [Dropdown] Overview title       |                                                                         Optional title to identify the dropdown menu*                                                                        |                                     “About Us”, “Get Involved” [7]                                    |
| [Dropdown] Overview description |                                                                  Optional description to better describe the dropdown menu*                                                                  |       “Mozilla is a global nonprofit dedicated to keeping…”, “From donating funds or data…” [8]       |
| Nav item                        |                                                               Navigation item (a link to an internal page or external resource)                                                              |           “Fellowships & Awards”, “Data Futures Lab”, “Responsible Computing Challenge” [9]           |
| Nav item description            |                                                                     Optional text to better describe the navigation item                                                                     | “Explore Approaches to Data Stewardship”, “A grant opportunity that empowers computing students” [10] |
| Featured section                |                                                                            Optional section with featured content                                                                            |                                    “Donate”, “Popular topics” [11]                                    |
| Featured section item           |                                                                           Navigation item within a featured section                                                                          |                                 “Make a donation”, “Ways to Give” [12]                                |

### Screenshots / mock-ups
![nav!UNITO-UNDERSCORE!1!UNITO-UNDERSCORE!annotated](https://github.com/MozillaFoundation/foundation.mozilla.org/assets/61277874/ea739eaf-4e73-4850-a055-8b90d878bba1)

![nav!UNITO-UNDERSCORE!2!UNITO-UNDERSCORE!annotated](https://github.com/MozillaFoundation/foundation.mozilla.org/assets/61277874/487d44fa-b11a-4406-a3b3-82c133b8cdb9)

![nav!UNITO-UNDERSCORE!3!UNITO-UNDERSCORE!annotated](https://github.com/MozillaFoundation/foundation.mozilla.org/assets/61277874/2c45f86b-c4de-4e48-a7d2-31134ad63e07)

#### Editor journey 
* [ ] As an editor, I can create and edit a navigation menu for our websites
* [ ] As an editor, I would like to have separate navigation menus for each site (foundation, mozfest) on our multi-site build so that we have more flexibility
* [ ] As an editor, I would like to have the ability of saving revisions of my navigation menus so that I can review them
* [ ] As an editor, I would like to have the ability of saving drafts of navigation menus so that I can edit the menus without affecting the website until I’m ready to publish
* [ ] As an editor, I would like to see a live preview of the navigation menu that I’m building as I’m building it
* [ ] As an editor, I need to be able to translate content on my navigation menu to all languages supported by the website

#### Permissions 
* [ ] As a site administrator, I want to control who can create, edit and delete navigation menus
* [ ] As a site administrator, I want to separately control who can set/activate a navigation menu for a site

#### Visitor journey 
* [ ] As a visitor, I want to see the navigation menu localized to my region and language preferences
* [ ] As a visitor, I want to see the navigation menu content in English if it is not available on my region/language

### Issues
* [x] #11979 
* [x] #11980
* [x] #11981 
* [x] #11982 
* [x] #12004 
* [x] #12005

┆Issue is synchronized with this [Jira Epic](https://mozilla-hub.atlassian.net/browse/TP1-54)
