### ISSUE TITLE
[Main Navigation Dropdown] Navigation item

### ISSUE THREAD

**Issue by jhonatan-lopes** [MozillaFoundation/foundation.mozilla.org#11979]
Implement the functionality for a `navigation item`.

# Acceptance criteria
- [ ] A navigation item is a reference to a resource
- [ ] A navigation item must have a title, which will be displayed in the corresponding column (“Fellowship & Awards”, “*Privacy Not Included”, etc.) – not for internal identification
- [ ] A navigation item can have an optional description
- [ ] Optional descriptions should not be displayed on mobile devices
- [ ] A navigation item needs to link to either a CMS page, a relative URL or an external link
- [ ] External links on a navigation item must be properly identified by using different rendering than internal links
- [ ] External links always open on a new tab

┆Issue is synchronized with this [Jira Story](https://mozilla-hub.atlassian.net/browse/TP-265)
