### ISSUE TITLE
[Main Navigation Dropdown] Navigation Menu

### ISSUE THREAD

**Issue by jhonatan-lopes** [MozillaFoundation/foundation.mozilla.org#11983]
Implement the "navigation menu" object for the main navigation dropdown.

# Acceptance criteria
- [ ] Editors can use a “navigation” menu on Wagtail CMS to create navigation objects/snippets
- [ ] Navigation objects are a collection of dropdowns
- [ ] Editors can build all items from a “create navigation” page, without having to leave the page to create dropdowns, columns and navigation items
- [ ] Editors can control the order in which dropdowns are displayed in a navigation menu

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/TP1-51)
