### ISSUE TITLE
[Main Navigation Dropdown] Column

### ISSUE THREAD

**Issue by jhonatan-lopes** [MozillaFoundation/foundation.mozilla.org#11980]
Implement a "column" for the main navigation dropdown.

# Acceptance criteria
- [ ] A column is a collection of navigation items
- [ ] A column must have a title, which will be displayed in the dropdown menu (“connect people”, “rally communities”, etc.)
- [ ] A column needs to have at least one navigation item
- [ ] A column can have at most four navigation items
- [ ] A column can have an optional "column button" with a customisable text (e.g. “see all research”)
- [ ] Editors can control the order in which navigation items are displayed in a column
- [ ] Wagtail UI: columns selector is shown between the “overview” and “featured column” sections so that it is intuitive (mirrors how it is going to be displayed)

┆Issue is synchronized with this [Jira Story](https://mozilla-hub.atlassian.net/browse/TP-266)
