### ISSUE TITLE
[Main Navigation Dropdown] Featured column

### ISSUE THREAD

**Issue by jhonatan-lopes** [MozillaFoundation/foundation.mozilla.org#11981]
Implement a "featured column" for the main navigation dropdown.

# Acceptance criteria
* [ ] A featured column is a type (child) of column (#11980), rendered differently
* [ ] Featured columns should always be rendered as the last item (right-most one on desktop, lowest one on mobile)
* [ ] Navigation items in a featured column cannot have descriptions
* [ ] Navigation items in a featured column need to have an icon

┆Issue is synchronized with this [Jira Story](https://mozilla-hub.atlassian.net/browse/TP1-53)
