### ISSUE TITLE
[Main Navigation Dropdown] Dropdown

### ISSUE THREAD

**Issue by jhonatan-lopes** [MozillaFoundation/foundation.mozilla.org#11982]
Implement the "dropdown" component for the main navigation.

# Acceptance criteria
- [ ] A dropdown is a collection of columns
- [ ] A dropdown needs to have at least one column
- [ ] A dropdown can have at most four columns
- [ ] A dropdown can have one optional featured column
- [ ] If a featured column is present, it will take the place of a regular column
- [ ] A dropdown object needs to have a title, which will be displayed in the navigation menu (“Who we are”, “What we do”, etc.)
- [ ] A dropdown can have an optional overview block, consisting of a title and a description. If an overview is provided, it needs to contain both an overview title and an overview description
- [ ] If an overview block is defined, it will take the place of one column
- [ ] A dropdown can have an optional "dropdown button" (call-to-action link with a customisable text) (e.g. “Learn more”)
- [ ] If a dropdown has both an overview and a CTA link, a CTA button will be displayed below the overview description (a card with overview title, overview description and CTA button)
- [ ] If a dropdown has a CTA link but no overview, the CTA button will be displayed at the bottom of the dropdown menu
Editors can control the order in which columns are displayed in a dropdown
- [ ] The overview must be the first item in a dropdown
