### ISSUE TITLE
[Main Navigation Dropdown] Navigation setting

### ISSUE THREAD

**Issue by jhonatan-lopes** [MozillaFoundation/foundation.mozilla.org#12004]
Build the navigation setting item for activating a navigation menu on wagtail.

# Acceptance criteria
* [ ] A navigation menu can be activated for a site through a Wagtail site setting
* [ ] A site administrator can go the relevant Wagtail setting and select a previously-built navigation menu for a specific site (“foundation”, “donate”, “mozfest”)
* [ ] Current hardcoded navigation menus are kept as a fallback in case there is no navigation menu activated for a specific site
* [ ] The chooser for the navigation menu only displays navigation menus in English (default language)

┆Issue is synchronized with this [Jira Story](https://mozilla-hub.atlassian.net/browse/TP1-38)
