### ISSUE TITLE
[Main Navigation Dropdown] NavLinkBlock

### ISSUE THREAD

**Issue by data-sync-user** [MozillaFoundation/foundation.mozilla.org#12006]
Implement a `NavLinkBlock` for a `navigation item`.

# Acceptance criteria
* [ ] A navigation item needs to link to either a CMS page, a relative URL or an external link
* [ ] External links on a navigation item must be properly identified by using different rendering than internal links
* [ ] External links always open on a new tab

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/TP-292)
