### ISSUE TITLE
[Main Navigation Dropdown] Blog dropdown

### ISSUE THREAD

**Issue by jhonatan-lopes** [MozillaFoundation/foundation.mozilla.org#12005]
Implement special dropdown for blog entries.

# Acceptance criteria
* [ ] Editors can opt-in to include a special dropdown menu for the blog
* [ ] The blog dropdown should render one column with the featured posts that are defined in the blog index page
* [ ] The blog dropdown should render one “featured column” with popular topics, defined in the blog index page
* [ ] The blog dropdown should render a CTA (column button) at its bottom with the text “see all blog posts”
* [ ] If a blog post title goes over the character limit (*define that), truncate it with ellipsis

┆Issue is synchronized with this [Jira Story](https://mozilla-hub.atlassian.net/browse/TP1-37)
