### ISSUE TITLE
Remove tag filtering from the IndexPage

### ISSUE THREAD

**Issue by Pomax** [MozillaFoundation/foundation.mozilla.org#6751]
This is an implementation epic based on https://github.com/mozilla/foundation.mozilla.org/issues/6371, and affects `BlogIndex` and `CampaignIndex` and consists of two main tasks.

### Switching from showing related posts based on tags

Switch to a "related posts" picker in the admin interface, using `related_posts` similar to PNI categories

- [x] add a `related_posts` field with pagechooser
- [x] write a save hook for blog posts so that if no related posts are set, the tag query runs and the result is used to set the real related posts
- [x] write a management command that runs this operation for each blog page.
- [x] update the blog template to use the new related posts field instead get_entries_by_tag

### Remove tag filtering for "recent blog entries" purposes.

- [ ] create an "indexable" page mixin so we have a master class to select on
- [ ] create a new blog entries picker component allows picking 1-or-more blog entries directly (using pagechooser)
- [ ] replace all the above-mentioned "recent-blog-entries-by-tag" with the blog entries picker component instead, set to the same blog entries as the tag search yields, then:
- [ ] remove tag filtering from the "recent blog entries" component

Note that this will only affect two pages:

1. Campaigns > Election integrity and platform accountability, filters on tags `platform policy tracker`, url: https://foundation.mozilla.org/campaigns/election-integrity-and-platform-accountability/
1. Mozilla Insights > *Privacy Included: Rethinking the Smart Home, filters on tag `privacy-included`, url: https://foundation.mozilla.org/en/insights/privacy-included/

Also note that this _only_ concerns tags. Categories should not be affected, with the "recent blog entires" component doing exactly the same as before when using category filtering.

### Notes

We will still allow tags on things like blog pages for SEO purposes.

**Comment by jamilasnell** [comment]
Make this into an Epic @Pomax!!! GOSH

**Comment by Pomax** [comment]
@tbrlpld @nancyt1 ideally the blog redesign, with updated categories and ontology work invalidates this issue entirely because the dev work includes throwing all of this now-obsolete-code away

**Comment by simont-cr** [comment]
Closing issue as part of the 2024 issue clean-up. Can be reopened if needed.
