### ISSUE TITLE
React Components Stylings

### ISSUE THREAD

**Issue by fessehaye** [MozillaFoundation/foundation.mozilla.org#7042]
Since react components use JSX and classnames we have to do an audit of what CSS classes they are using and replace them with tailwind!

## Dev Work
* [ ] Make sure there is no bootstrap classes remaining on the JSX file
* [ ] If there are CSS classes that are from a local SASS file, refactor them on the JSX file using tailwind classes
* [ ] After refactoring the classes from SASS files, delete the previous SCSS file
* [ ] Might be needed to create a plugin if we are replacing a reused bootstrap class

## Acceptance Criteria
* [ ]  Component should be able to work without a dependency from bootstrap
* [ ]  Component should be able to work without a dependency from existing SASS files

┆Issue is synchronized with this [Jira Story](https://mozilla-hub.atlassian.net/browse/TP1-245)

**Comment by cdanfon** [comment]
After chatting with @fessehaye during Grooming this ticket should become an epic.

**Comment by simont-cr** [comment]
Moving away from bootstrap is being considered on issue #6989.
