### ISSUE TITLE
SEO | Duplicate meta descriptions

### ISSUE THREAD

**Issue by bheasman** [MozillaFoundation/foundation.mozilla.org#8442]
# Original description

Off the back of the Grassriots site audit, it has been identified that there are a number of issues with duplicate meta descriptions on pages

Detail from Grassriots:
Most pages listed in this set are using a default meta desctiption such as "Mozilla is a global nonprofit dedicated to keeping the Internet a global public resource that is open and accessible to all." According to the crawler - It is better to have no meta description at all than to have a duplicate one. Duplicate meta descriptions on different pages mean a lost opportunity to use more relevant keywords. Also, duplicate meta descriptions make it difficult for search engines and users to differentiate between different webpages

Link to the [audit](https://docs.google.com/spreadsheets/d/15HwgpxSYc4Zl809kcebAhLfLYXFuIk8ZP-Qvk3yVV8Q/edit#gid=627737737)

# Description

Based on the above description, I guess we would rather a page has no meta description instead of a default one. We should therefore update the handling of the meta description to not use a default. Rather, when the editors do not provide a meta description, don't add the field in the template. 

# Acceptance criteria

- [ ] Each page uses the meta description that is added to the page by the editors or does not use any meta description. 

# Dev tasks

- [ ] Find the logic that adds default meta descriptions to the pages. 
- [ ] Adjust the logic so that only editor provided meta descriptions are added into the pages.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/TP1-268)

**Comment by bheasman** [comment]
Thanks @tbrlpld - looks good. It looks like Google tends to do a pretty good job of showing something relevant on the search listings page when there is no meta description set - so it seems like this might have a benefit to CTR than having something generic too.

**Comment by bheasman** [comment]
In terms of re-running the tool - we'd probably want to go back to grassriots to re-run things once we've addressed the key issues they highlighted
