### ISSUE TITLE
Audit Github issue templates

### ISSUE THREAD

**Issue by cdanfon** [MozillaFoundation/foundation.mozilla.org#8626]
# Description
The existing GitHub issue templates have become a bit stale. We should review what we have a perform a little bit of spring cleaning. Update the useful ones, remove the unused ones. Make sure we share the same set of templates across the different repos. All issue templates should contain the sections "Description", "Acceptance criteria" and "Tasks". 

# Acceptance criteria
* [ ] We have a list of the existing issue templates across all the different repositories.
* [ ] For each template we have a know how useful they are and if they should be kept.
* [ ] We know which teams depend on which issue templates. 
* [ ] We have tickets to delete the unnecessary templates.
* [ ] We have tickets to update the useful but tickets (where necessary).
* [ ] We have tickets to create the same set of issue templates across all the different repositories. 

# Tasks
* [ ] Review information about what constitutes "good tickets/issues".
* [ ] Gather a list of all the available issue templates used across the different repositories. 
* [ ] Try to see if there is a way to get information on which of these templates are still used. 
* [ ] Check-in with the different teams to see which issue templates they are using and what their requirements and use cases are. 
* [ ] Review all the existing tickets and rate their usefulness against "good tickets" and the requirements of the teams. 
* [ ] Create follow up tickets to remove the not needed templates. 
* [ ] Create follow up tickets to update the needed template that don't meed the standards of "good tickets".

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/TP1-273)

**Comment by mtdenton** [comment]
@cdanfon interested to hear more about this and how it may have evolved since earlier this year.

**Comment by cdanfon** [comment]
Hey @tbrlpld unfortunately this is something that hasn't really evolved that much since then. A good candidate for one of the maintenance days!

**Comment by tbrlpld** [comment]
@cdanfon I think you meant to mention @mtdenton

**Comment by tbrlpld** [comment]
Why is this unplanned? @cdanfon

**Comment by cdanfon** [comment]
Oh yes I did! 

This is not planned into any sprints right?

**Comment by mtdenton** [comment]
Regardless, I really like the idea of dredging this one up out of the backlog, seems like a perfect candidate for Maintenance Day™

**Comment by tbrlpld** [comment]
Agreed, this would be good for a maintenance day. 

I am a bit confused about having a Milestone. I was under the impression that we wanted to use Epics instead. Has this changed again?

**Comment by cdanfon** [comment]
Hey @tbrlpld 

Agreed we should use Epics for projects, such as PNI, Blog improvements etc. 

Using the Maintenance milestone is a way of having an ordered backlog for Maintenance tasks in a different place other than the main board but that is not necessarily a project itself (such as PNI for example).

This is a one-off instance where we use milestones. The idea is that each quarter we will have a maintenance milestone. 

On Maintenance days you just go there and pick up items from the top of the backlog. 

You're also welcome to include tickets in the milestone if you think they'd be relevant, @mtdenton would be the one prioritising these. 

@danielfmiranda @mmmavis @fessehaye for reference. I will document this in Confluence.

**Comment by tbrlpld** [comment]
If the ordered list is the reason for the Milestone, Epics have that ability too:

E.g. see the list of issues in here:
https://app.zenhub.com/workspaces/mofo-engagement-585335eab729771d0736378d/issues/mozilla/foundation.mozilla.org/8801

The ordering is done on the board and is synced between board and the list. E.g. see this. 
https://app.zenhub.com/workspaces/mofo-engagement-585335eab729771d0736378d/board?epics=Z2lkOi8vcmFwdG9yL0VwaWMvOTMzOTY2
