### ISSUE TITLE
Update source\js\components\pulse-profile\pulse-profile.jsx

### ISSUE THREAD

**Issue by fessehaye** [MozillaFoundation/foundation.mozilla.org#8710]
See [[EPIC] React Components Stylings](https://github.com/mozilla/foundation.mozilla.org/issues/7042) for more details.

## Dev Work

- [ ] Make sure there is no bootstrap classes remaining on the JSX file
- [ ] If there are CSS classes that are from a local SASS file, refactor them on the JSX file using tailwind classes
- [ ] After refactoring the classes from SASS files, delete the previous SCSS file
- [ ] Might be needed to create a plugin if we are replacing a reused bootstrap class

## Acceptance Criteria

- [ ]  Component should be able to work without a dependency from bootstrap
- [ ]  Component should be able to work without a dependency from existing SASS files

**Comment by simont-cr** [comment]
Closing per issue clean-up on EPICS.
