### ISSUE TITLE
Clean up source/sass/views/youtube-regrets-2021.scss

### ISSUE THREAD

**Issue by danielfmiranda** [MozillaFoundation/foundation.mozilla.org#8734]
The goal of this ticket is to take all the styling defined in youtube-regrets-2021.scss file, and update the related HTML elements to use tailwind classes to achieve the same design.

Some of the HTML templates that may need to be updated include:

- [ ] youtube_regrets_page_2021.html
- [ ] youtube_regrets_2021.html
- [ ] fragments/quote.html
- [ ] fragments/categories.html
- [ ] fragments/our-research.html
- [ ] fragments/accordion_section_3.html
- [ ]  fragments/youtube_regrets_acorrdion.html
- [ ]  fragments/accordion_heading_button.html
- [ ]  fragments/downloads.html
- [ ]  fragments/recommendations.html

---
### Dev Steps:

- [ ] Update templates to use tailwind classes to match their designs
- [ ] Remove SCSS classes that are no longer needed
- [ ] If everything in the scss file was able to be replaced with tailwind classes, delete the file

**Comment by simont-cr** [comment]
Closing per issue clean-up on EPICS.
