### ISSUE TITLE
Clean up source/sass/views/youtube-regrets-2021-carousel.scss

### ISSUE THREAD

**Issue by danielfmiranda** [MozillaFoundation/foundation.mozilla.org#8736]
The goal of this ticket is to take all references of the scss in the youtube-regrets-2021-carousel.scss file, and instead update the related HTML elements to use tailwind classes to achieve the same design.

Some of the HTML templates that may need to be updated include:

- [ ] youtube-regrets-2021/fragments/carousel_controls.html
- [ ] youtube-regrets-2021/fragments/carousel.html
- [ ] youtube-regrets-2021/fragments/hero_carousel.html

**Comment by simont-cr** [comment]
Closing per issue clean-up on EPICS.
