### ISSUE TITLE
Clean up source/sass/views/youtube-regrets-2021-carousel-hero.scss

### ISSUE THREAD

**Issue by danielfmiranda** [MozillaFoundation/foundation.mozilla.org#8737]
The goal of this ticket is to take all references of the scss in the youtube-regrets-2021-carousel-hero.scss file, and instead update the related HTML elements to use tailwind classes to achieve the same design.

Some of the HTML templates that may need to be updated include:

- [ ] youtube-regrets-2021/fragments/hero_carousel.html

---
### Dev Steps:

- [ ] Update templates to use tailwind classes to match their designs
- [ ] Remove SCSS classes that are no longer needed
- [ ] If everything in the scss file was able to be replaced with tailwind classes, delete the file

**Comment by simont-cr** [comment]
Closing per issue clean-up on EPICS.
