### ISSUE TITLE
clean up source/sass/views/dear-internet.scss

### ISSUE THREAD

**Issue by danielfmiranda** [MozillaFoundation/foundation.mozilla.org#8738]
The goal of this ticket is to take all references of the scss in the dear-internet.scss file, and instead update the related HTML elements to use tailwind classes to achieve the same design.

Some of the HTML templates that may need to be updated include:

- [ ] dear_internet_page.html
- [ ] dear_internet_cloud.html

---
### Dev Steps:

- [ ] Update templates to use tailwind classes to match their designs
- [ ] Remove SCSS classes that are no longer needed
- [ ] If everything in the scss file was able to be replaced with tailwind classes, delete the file

**Comment by simont-cr** [comment]
Closing per issue clean-up on EPICS.
