### ISSUE TITLE
Clean up source/sass/buyers-guide/components/header.scss

### ISSUE THREAD

**Issue by danielfmiranda** [MozillaFoundation/foundation.mozilla.org#8739]
The goal of this ticket is to take all references of the scss in the header.scss file, and instead update the related HTML elements to use tailwind classes to achieve the same design.

Some of the HTML templates that may need to be updated include:

- [ ] templates/buyers_guide/bg_base.html
- [ ] pni_mobile_nav.html
- [ ] multi_page_nav_mobile.html

---
### Dev Steps:

- [ ] Update templates to use tailwind classes to match their designs
- [ ] Remove SCSS classes that are no longer needed
- [ ] If everything in the scss file was able to be replaced with tailwind classes, delete the file

**Comment by danielfmiranda** [comment]
Note for when we estimate points for this ticket: Since the nav components seem to have some JS files that work alongside them, this might take a longer than usual to clean up as we have to make sure everything is still working the same after as well.

**Comment by simont-cr** [comment]
Closing per issue clean-up on EPICS.
