### ISSUE TITLE
Clean up creepometer.scss

### ISSUE THREAD

**Issue by danielfmiranda** [MozillaFoundation/foundation.mozilla.org#8749]
The goal of this ticket is to take all references of the scss in the creepometer.scss file, and instead update the related HTML elements to use tailwind classes to achieve the same design.

Some of the HTML templates that may need to be updated include:

- [ ] creepometer.jsx

---
### Dev Steps:

- [ ] Update templates to use tailwind classes to match their designs
- [ ] Remove SCSS classes that are no longer needed
- [ ] If everything in the scss file was able to be replaced with tailwind classes, delete the file
- [ ] If file was deleted, remove it from bg-main.scss

**Comment by simont-cr** [comment]
Closing per issue clean-up on EPICS.
