### ISSUE TITLE
[Blog] - [Search] - Render number of results

### ISSUE THREAD

**Issue by danielfmiranda** [MozillaFoundation/foundation.mozilla.org#8773]
The goal of this ticket is to implement a method in the backend that returns the number of entries after a search. 

We should then render the number of entries on the new template made in #8772 

At this time, styling is not needed, just returning the string "Showing x results:" will suffice! 

## Dev Steps:
* [ ] After a search, get the number of results from the backend
* [ ] Render it in the new template

## Acceptance Criteria:
* [ ] If a search has been preformed, this item should render above the search bar returning the number of results.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/TP1-276)

**Comment by cdanfon** [comment]
Hey @nancyt1 we were discussing this ticket in grooming and wondered whether the term 'showing' might be confusing to users as they are going to be displaying the first 6 results by default even if the search query might return 100.

**Comment by nancyt1** [comment]
@cdanfon Yes, thank you to whoever brought this up, I also agree that it's confusing! I've now updated all the mockups to say "X results for:".

**Comment by simont-cr** [comment]
Hi @cdanfon , is this something that should be kept as an improvement for this year work or has become outdated with latest changes to the platform?

**Comment by cdanfon** [comment]
Hey Simon,

I'm pretty out of the loop with regards to features - probably best to
check with Kristina/Tyler!
