### ISSUE TITLE
[Blog] - [Search] - Sorting Functionality

### ISSUE THREAD

**Issue by danielfmiranda** [MozillaFoundation/foundation.mozilla.org#8777]
![](https://user-images.githubusercontent.com/18314510/169924804-d0a956d9-2fd5-46f2-ad39-bce036c1ad76.png)

The goal of this ticket is to add a dropdown input next to the search bar , and have the data be sortable by Latest, Oldest, and Most relevant.

Here are the Search Field Rankings sent to us by stakeholders:

1. Title
1. Category
1. Author
1. Tags
1. Description/Preview Text/body text
1. Date
1. Language

## Dev Steps
* [ ] Create new template under /fragments/
* [ ] Add this template to the main search page template
* [ ] Get sort functionality working
* [ ] Design the component using the screenshot above, using tailwind classes as much as you can

## Acceptance Criteria:
* [ ] Users can use this drop down to sort the results by Latest, Oldest, and Most relevant

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/TP1-277)
