### ISSUE TITLE
[Blog] - [Topic Detail] - Filtered Posts

### ISSUE THREAD

**Issue by danielfmiranda** [MozillaFoundation/foundation.mozilla.org#8792]
<img width="575" alt="image" src="https://user-images.githubusercontent.com/18314510/169954972-7c960014-b70e-46fa-94b0-442c4d53e1eb.png">

The goal of this ticket is to create the template that is going to house the 9 filtered by topic blog posts, using the new blog card from #8726 

Please note: The Image above shows 8 results with the "related topics" cutout box, this is not needed at the moment as it is P2. 

Dev Tasks
---

- [ ] Create new template to house the component
- [ ] Render the 9 Initial filtered posts using the blog card component #8726
- [ ] Add a "load more" button that will append 9 new posts to the list when clicked

Acceptance Criteria
---

- [ ] The cards display blog posts that are tagged with the specific topic
- [ ] The Cards display as expected at all breakpoints
- [ ] The user can load more results by clicking the button

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/TP1-281)
