### ISSUE TITLE
[Blog] - Author Detail Page

### ISSUE THREAD

**Issue by danielfmiranda** [MozillaFoundation/foundation.mozilla.org#8795]
![](https://user-images.githubusercontent.com/18314510/171499585-c03f60ea-a5e1-41ea-9201-1aee602d6796.png)

[link to figma designs](https://www.figma.com/file/528nyaJFzvCXAiw2gglwzh/Blog-Improvements?node-id=953%3A34419)

This epic was created to house the work that is needed to create the blog author detail page 

I believe the order we should do these tickets in are as follow:

1. #8796 
1. #8797 
1. #8798 
1. #8799

Acceptance Criteria:

* [ ] Users can visit a detail page for blog authors
* [ ] This page has a header that displays the Authors Name, Image, and Description
* [ ] This new pages header should also render the new #8790 and #8778 
* [ ] Underneath the header, the page should render 9 of the authors latest blog posts
* [ ] If applicable, a load more button should render, which will append 9 more items to the list.

┆Issue is synchronized with this [Jira Epic](https://mozilla-hub.atlassian.net/browse/TP1-284)

**Comment by kristinashu** [comment]
Note: no need for Twitter embed
