### ISSUE TITLE
[Blog] - [Author] - Author Details Header

### ISSUE THREAD

**Issue by danielfmiranda** [MozillaFoundation/foundation.mozilla.org#8797]
<img width="533" alt="image" src="https://user-images.githubusercontent.com/18314510/171496813-c66acb43-1579-4cb7-890e-aaaa317a9c91.png">

The goal of this ticket is to create a new fragment template for the header section of the author detail page. 

Please note that the social buttons are to be implemented at a later date.

Dev Steps:
---

- [ ] Create new HTML template for component
- [ ] Include the Breadcrumbs Component #8790 
- [ ] Include the Search Bar Component #8778 
- [ ] Render and style the authors name, image, and bio.
- [ ] Include this component in the Author Detail Page template #8796 

Acceptance Criteria:
--- 
- [ ] Bread Crumbs
- [ ] Author name
- [ ] Author Bio
- [ ] Author image
- [ ] Search Bar

**Comment by danielfmiranda** [comment]
Hi @nancyt1! I was wondering if you could please help with a question regarding this ticket? 

In this ticket’s mock ups, I see that there are social media buttons. At the moment, author profiles do not have any fields for social media platforms.

We can add these, but should they be required? Or should we only render buttons for social media handles that they save.

Also, I see that the “copy to clipboard” button is in the mockups. Do we want to include that?

Thank you in advance!

**Comment by danielfmiranda** [comment]
Leaving a note that after discussing with design, we have decided to  omit the social media buttons until a later date!

**Comment by danielfmiranda** [comment]
Hi @nancyt1! 

This feature has now been merged into staging and is ready for QA, can you please take a look here https://foundation.mofostaging.net/en/blog/authors/daniel-miranda-646/ and confirm if everything looks OK? 

Thanks in advance!

**Comment by kristinashu** [comment]
Yay thank you @danielfmiranda! Do you know if there's a follow up ticket to make the names on /blog and /blog/[post] clickable? I think they were clickable but then it was removed because they didn't go anywhere but I guess we'll be ready to make them clickable again!

**Comment by danielfmiranda** [comment]
Hi @kristinashu! 

I have just taken a look at our repo's issues and see no tickets related to making the author names clickable. I can definitely create one for us, however, I am wondering whether the ticket should be marked as blocked until the Author Detail Page is complete, or, if its good to go now?

**Comment by kristinashu** [comment]
Yes thank you Daniel, that makes sense!

**Comment by nancyt1** [comment]
@danielfmiranda Everything looks good to me! Thank you Daniel!

**Comment by danielfmiranda** [comment]
Great! Thanks both @kristinashu @nancyt1 , going to move this ticket to "Ready for Production" now, and will create those tickets!
