### ISSUE TITLE
[Blog] - [Author] - Author Detail Page Styling

### ISSUE THREAD

**Issue by danielfmiranda** [MozillaFoundation/foundation.mozilla.org#8799]
![](https://user-images.githubusercontent.com/18314510/171498916-e78ed129-ee1a-47de-bd14-c3cf49219616.png)

The goal of this ticket is to take the template created from #8796, which now includes the Header Component #8797  as well as the Authors Blog Posts component #8798, and style the template using tailwind classes to match the design above as much as possible.

## Dev Steps:
* [ ] Using tailwind classes, style the template to match the design as close as possible on all breakpoints

## Acceptance Criteria:
* [ ] Page should be using new components #8797 and #8722
* [ ] Page layout and design should follow image above, or design in figma using tailwind classes as much as possible

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/TP1-286)
