### ISSUE TITLE
Improve publishing error message for staff

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/foundation.mozilla.org#8833]
Staff sometimes see the error message "We Are Undergoing Maintenance" when they are trying to publish a page.

The word seems misleading since the issue, I believe, is typically due to a problem with content they have added e.g. an image is too large of a file size.

Is it possible to show working that is more specific? 

via tbrlpld in [Slack](https://mozilla.slack.com/archives/C98GW3P7X/p1653668010380769?thread_ts=1653499962.045269&cid=C98GW3P7X):

> Yea, the wording is kind of odd. I have to check, but I think this should be the 500 error page. I am not sure it's possible to point out what exactly is wrong, as the same template has to respond to all 500 server errors. But, we should not pretend we are doing maintenance when it's really a server error. That's quite confusing and has come up a few times in the past weeks

Screen cap of what staff see:
![image](https://user-images.githubusercontent.com/1068783/171460333-cb888e95-5b0b-47cc-9b79-371d1bf19ad3.png)

### Todo
* [ ] Investigate what type of errors staff commonly experience
* [ ] Investigate to see how specific we can be with our error message
* [ ] Open a new ticket for implementation

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/TP1-291)

**Comment by simont-cr** [comment]
@kristinashu Is this still an issue that the team is encountering? If it does, I do think that proper error messaging would be at least a P2.

**Comment by kristinashu** [comment]
P2 sounds good

**Comment by data-sync-user** [comment]
➤ Simon Acosta Torres commented:

Ties to https://mozilla-hub.atlassian.net/browse/TP1-315 ( https://mozilla-hub.atlassian.net/browse/TP1-315|smart-link ) , duplicate ticket, abandoning this one.
