### ISSUE TITLE
Refactor index page and its child page types

### ISSUE THREAD

**Issue by tbrlpld** [MozillaFoundation/foundation.mozilla.org#9080]
## Description
The `IndexPage` provides quite a bit of functionality. It has a method to provide all its child pages from cache or from the database. There is pagination/load more functionality.  There is filtering of entries by tags. 

The `IndexPage` is also the parent page of other index like pages, most notably the `BlogIndexPage`. 

Unfortunately, I believe some design decisions make the `IndexPage` (and by extension the `BlogIndexPage` more complex than necessary). For example the filtering. A specific route/method `entries_by_tag` exists to filter the index content. But rather than using the basic queryset and filtering it and overriding the template context, some flags are set on the page type itself, which is then supposed to be picked up by `get_entries` to return the filtered content. This seems like it is the wrong way around. The general methods should not need to know about the filtering use case. 

This complexity is also evident in the existence of two methods with very unclear differentiation `get_entries` and `get_all_entries`. The difference becomes even muddier when child classes override one or the other to create even more specialized filtering cases (e.g. the topics route on the `BlogIndexPage`). 

I would suggest to refactor `IndexPage` (and it's child pages where necessary) to make their future maintenance easier. The exact details would need to be spiked, but the main ideas would be that parent classes should not know about their children and that general methods (return all child pages) should not cater to special cases (return only a subset of the child pages).

I would also suggest that every case where filtering is done in Python should be re-evaluated. It seems to be causing errors (see #6255) while being inefficient and unnecessary, since this kind filtering should be best done at database level whenever possible. 

This all should be accompanied by adding sufficient test coverage (so far, only test for the `BlogIndexPage` exist, and those have only been added recently -- see #9043 for example)

## Tasks
* [ ]  Create tests for the existing functionality for the different index page types. #10152 
* [ ]  Figure out how the offset pagination can work.
  * I think there is a way with overriding the `Paginator.count` and `[Paginator.page](http://Paginator.page)` methods.
  * The rest should still be able to function.
  * I guess I could also roll the expandable functionality into this…. although that would involve the `Page` model too.
  * This already works in the subclass “BlogIndex”, but that one relies on the custom pagination instead of the Django paginator class. That’s why change for that is needed… or the blog page needs to completely do it’s own pagination… but that would be weird.
* [ ]  Remove the `newsletter-callout-box` template block override. This is only needed on the blog index. You can extend existing blocks in the template with `block.super`.
* [ ]  Add slug field to blog topics to allow proper querying.
* [ ]  Use page locale if the locale is needed. We are currently checking the locale from the request over and over again. That does not seem necessary, because the served page already known it’s own locale.
* [ ]  `entry_cards_item_loop.html` template should probably not do the card type switching. If this needs to be specified per page, then it should be on the page type and passed to the template as a variables, instead of this `if type == ...` check in the template.
* [ ]  Merge editorial content index page with the new index page

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/TP1-298)
