### ISSUE TITLE
YouTube RegretsReporter Dataset page

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/foundation.mozilla.org#9967]
Brandi would support in creating a cms to host 2 RegretsReporter datasets that will be released publicly.

### Notes
- Page layout: intro section to describe the dataset, maybe an accordion FAQ section, and then the form
- ~People will fill out a Typeform then we will give them access to the data~
- Jesse is preparing the datasets
- Brandi's planning and copy [doc](https://docs.google.com/document/d/1sHkUSaHC6LY8PcKRJZT2ezaMHw3zPiIOdXfBZ7v9_Rs/edit?usp=sharing) 
- ~Draft copy should be ready Jan 20~
- ~Launch date: Feb 15~
- It will be under /youtube but we can also create a landing page in the Research hub
- It more complex but note the [CV data set page](https://commonvoice.mozilla.org/en/datasets)

### Todo
- [x] Set up [landing page](https://foundation.mozilla.org/en/youtube/regretsreporter-dataset/) in CMS with placeholder copy
- [x] Stakeholders to update copy on /youtube and the new page
- [x] Create one new graphic for https://github.com/MozillaFoundation/foundation.mozilla.org/issues/10548
  - Thumbnail on /youtube 
  - Banner image for new page
  - OG image for new page
  - Link to out to Github repo
- ~Style Google Doc with Mozilla branded template, optimize for accessibility, export as PDF for Github repo similar to https://github.com/PAIR-code/datacardsplaybook/blob/main/templates/DataCardsExtendedTemplate.pdf~

**Comment by kristinashu** [comment]
Project has shifted a bit but I've created [this slide](https://docs.google.com/presentation/d/16SwlDQ-pFP1wsDQAlcimk0kE-62x7Lj7j4596NIH5Ts/edit#slide=id.g25275a8168_1_450) to try to align on the user flow.

**Comment by kristinashu** [comment]
This project has shifted a lot, my latest understanding is:

For [foundation.mozilla.org/youtube/](http://foundation.mozilla.org/youtube/)
- Stakeholders can [update the copy on the page](https://foundation.mozilla.org/cms/pages/15076/edit/) once they have it
- Sabrina to create a new illustration for the thumbnail

For the new dataset landing page that will eventually be at [foundation.mozilla.org/youtube/regretsreporter-dataset](http://foundation.mozilla.org/youtube/regretsreporter-dataset)
- Stakeholders can [update the copy on the page](https://foundation.mozilla.org/cms/pages/21685/edit/#tab-content) once they have it
- Sabrina to create a new illustration for the top banner & OG image

We can add the links out to the Hugging Face page from the two pages mentioned above once the stakeholder has created it. It is unclear to me how much the Hugging Face page can be branded or customized but will provide need any logos, illustrations, or colors if needed
